# redis设置
# redis options
[db.redis]
    addr = "localhost:6379"
    db = 0

[options]
    # http服务监听地址
    # http service listen addr
    httpAddr = [":8081"]

    # redis中的key前缀
    # key prefix in redis
    redisPrefix = "urlshort:"

    # key包含的字符
    # key contains characters
    keyCharMap = "abcdefghjkmnpqrstwxyz23456789"

    # key的长度
    # key length
    keyLength = 3

    # 如果key冲突了，重试次数
    # number of retries in case of key conflict
    retryCount = 1000

[options.security]
    # 访问token，可以多个
    # access token
    token = ["000000"]